############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Me"
url = "about/"
weight = 2

[[main]]
name = "CV"
url = "cv/"
weight = 3

[[main]]
name = "Photography"
weight = 4
hasChildren = true

[[main]]
parent = "Photography"
name = "Astro"
url = "astro/"

[[main]]
parent = "Photography"
name = "Street"
url = "street/"

[[main]]
name = "Blog"
url = "blog/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6

[[main]]
weight = 7
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Categories"
url = "categories/"

# footer menu
[[footer]]
name = "About Me"
url = "about/"
weight = 1

[[footer]]
name = "CV"
url = "cv/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weigth = 3

